version: '3.8'
services:
  app:
    container_name: lm-test
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - ENV=develop

    restart: on-failure
    volumes:
      - .:/app
    networks:
      - fullstack

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    external: true
    driver: bridge
